server:
  port: 7902

spring:
  application:
    name: EurekaServer
  security:
    user:
      name: zhangxiang
      password: 123
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.com:7900/eureka/, http://euk2.com:7901/eureka/
  instance:
    hostname: euk3.com
